server:
  port: 8086


## apollo相关配置
#app:
#  id: update_service                            #应用ID
#apollo:
##  cacheDir: /opt/data/                      #配置本地配置缓存目录
#  cluster: default                           #指定使用哪个集群的配置
#  meta: http://106.14.1.219:8100             #DEV环境配置中心地址
#  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
#  bootstrap:
#    enabled: true                            #是否开启 Apollo
#    namespaces: application                  #设置 Namespace
#    eagerLoad:
#      enabled: false                         #将 Apollo 加载提到初始化日志系统之前
#
# 配置mysql
spring:
  datasource:
    url: jdbc:mysql://106.14.1.219:3306/update_service
    username: test
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
    primary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false